<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'appLms' => array($baseDir . '/html'),
    'appCore' => array($baseDir . '/html'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
);
