<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'appLms' => array(_base_),
    'appCore' => array(_base_),
    'Twig_' => array(_addons_ . '/twig/twig/lib'),
);
