<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'appLms' => array($baseDir . '/'),
    'appCore' => array($baseDir . '/'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
);
